---
abstract: 'A simple log to console for DBIC querylogs'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-DBIC-ConsoleQueryLog
requires:
  Catalyst: '5.90060'
  Moo::Role: '2.003002'
  Text::SimpleTable: '2.03'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-Plugin-DBIC-ConsoleQueryLog/issues
  homepage: https://github.com/jjn1056/Catalyst-Plugin-DBIC-ConsoleQueryLog
  repository: https://github.com/jjn1056/Catalyst-Plugin-DBIC-ConsoleQueryLog.git
version: '0.001'
x_serialization_backend: 'YAML::Tiny version 1.70'
